name: table_calendar_waldlust
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.0
author: Hojin Ahn <jinahn4234@gmail.com>
homepage: https://github.com/hojinahn4234/table_calendar_waldlust

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
